### ISSUE TITLE
Error while saving the COCO format

### ISSUE THREAD

**Issue by TemitopeOladokun** [Tony607/labelme2coco#3]
Hello @Tony607, thank you for the conversion script.
Can you explain why I got this error?

save coco json
Traceback (most recent call last):
  File "/content/labelme2coco/labelme2coco.py", line 163, in <module>
    labelme2coco(labelme_json, args.output)
  File "/content/labelme2coco/labelme2coco.py", line 27, in __init__
    self.save_json()
  File "/content/labelme2coco/labelme2coco.py", line 137, in save_json
    self.data_transfer()
  File "/content/labelme2coco/labelme2coco.py", line 33, in data_transfer
    self.images.append(self.image(data, num))
  File "/content/labelme2coco/labelme2coco.py", line 51, in image
    img = utils.img_b64_to_arr(data["imageData"])
  File "/usr/local/lib/python3.6/dist-packages/labelme/utils/image.py", line 18, in img_b64_to_arr
    img_data = base64.b64decode(img_b64)
  File "/usr/lib/python3.6/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.6/base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

**Comment by sanariaz154** [comment]
how did you solve this issue?
