### ISSUE TITLE
Error while saving JSON file

### ISSUE THREAD

**Issue by TemitopeOladokun** [Tony607/labelme2coco#4]
Hello @Tony607 , thank you for the script but while running the script I got this error.
What am I doing wrong?

save coco json
Traceback (most recent call last):
  File "/content/labelme2coco/labelme2coco.py", line 163, in <module>
    labelme2coco(labelme_json, args.output)
  File "/content/labelme2coco/labelme2coco.py", line 27, in __init__
    self.save_json()
  File "/content/labelme2coco/labelme2coco.py", line 137, in save_json
    self.data_transfer()
  File "/content/labelme2coco/labelme2coco.py", line 33, in data_transfer
    self.images.append(self.image(data, num))
  File "/content/labelme2coco/labelme2coco.py", line 51, in image
    img = utils.img_b64_to_arr(data["imageData"])
  File "/usr/local/lib/python3.6/dist-packages/labelme/utils/image.py", line 18, in img_b64_to_arr
    img_data = base64.b64decode(img_b64)
  File "/usr/lib/python3.6/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.6/base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

**Comment by nklein23** [comment]
@TemitopeOladokun were you able to solve the issue? I'm having the same problem.

**Comment by TemitopeOladokun** [comment]
Yes, I solved the problem @NiklasDL .

**Comment by nklein23** [comment]
> Yes, I solved the problem @NiklasDL .

Would you mind telling me how you did that?

**Comment by TemitopeOladokun** [comment]
Check this out @NiklasDL. 
https://github.com/TemitopeOladokun/Labelme-

**Comment by sanariaz154** [comment]
hi @TemitopeOladokun  . The link you shared i no longer working. would you mind sharing your solution here ?
